# Generated by Django 4.0.6 on 2022-08-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=256)),
                ('credits', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('overview', models.CharField(max_length=1800)),
                ('preReqs', models.CharField(max_length=1800)),
                ('skippable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Optii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crsName', models.CharField(max_length=1024)),
                ('provider', models.CharField(max_length=1024)),
                ('fullfillment', models.ForeignKey(limit_choices_to={'skippable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='Schedule_Map.courses')),
            ],
        ),
    ]
