# Generated by Django 4.0.6 on 2022-08-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_Map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optii',
            name='fullfillment',
            field=models.ForeignKey(default='Not offered in WWP', limit_choices_to={'skippable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='Schedule_Map.courses'),
        ),
    ]
