# Generated by Django 4.0.6 on 2022-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_Map', '0002_alter_optii_fullfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='optii',
            name='testing',
            field=models.CharField(default='No Test Required', max_length=128),
        ),
    ]
