# Generated by Django 4.0.6 on 2022-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_Map', '0005_alter_optii_fullfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='classType',
            field=models.CharField(default='Elective', max_length=128),
        ),
    ]
